# Generated by Django 5.2.3 on 2025-07-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_total_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinventory',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sellerprofile'),
        ),
    ]
