# Generated by Django 5.2.3 on 2025-07-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sellerinventory_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinventory',
            name='profile',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order'),
        ),
    ]
