# Generated by Django 5.2.3 on 2025-07-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_sellerinventory_profile_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinventory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.sellerprofile'),
        ),
    ]
