# Generated by Django 5.2.3 on 2025-07-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sellerinventory_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='mesage',
            new_name='message',
        ),
    ]
