# Generated by Django 5.2.3 on 2025-12-11 08:35

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default=api.utils.generate_random_code, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=api.utils.generate_random_code, max_length=6),
        ),
    ]
