# Generated by Django 5.2.3 on 2025-12-11 08:36

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_cart_code_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default=api.utils.generate_random_code, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=api.utils.generate_random_code, max_length=6, unique=True),
        ),
    ]
