# Generated by Django 5.2.3 on 2025-12-11 08:42

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_cart_cart_code_alter_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=api.utils.generate_random_code, max_length=6),
        ),
    ]
