# Generated by Django 5.2.3 on 2025-12-11 08:42

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=api.utils.generate_random_code, max_length=6, unique=True),
        ),
    ]
